=== Sravani-Sravani/Java-Full-Stack-Development/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/XML-Demo/external.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student)+>
<!ELEMENT student (id+,name+,gender+,department+)>
<!-- <!ATTLIST student gender CDATA #IMPLIED> -->
<!-- <!ATTLIST student gender CDATA #FIXED "female"> -->
<!-- <!ATTLIST student gender CDATA (Male|Female|Others #REQUIRED> -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ENTITY KLU "KL University">
<!ELEMENT department ANY> <!-- EMPTY  -->

=== Sravani-Sravani/Java-Full-Stack-Development/XML-Demo/WebContent/External_DTD_Demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  PUBLIC - from online or from any other resources -->
<!DOCTYPE students SYSTEM "external.dtd"[

<!ENTITY KLU "KL University">

]>
<students> 

<student>
<id>&apos;1900300001&apos;</id>
<name>Sravani</name>
<gender>Female</gender>
<department>CSE</department>
</student>

<student>
<id>1900300002</id>
<name>PEACE</name>
<gender>female</gender>
<department>CSE</department>
</student>

<student>
<id>1900300003</id>
<name>&KLU;</name>
<gender>female</gender>
<department>ECE</department>
</student>

</students>
